/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edwardyung_jnilbs_c_jnilbs_MainActivity */

#ifndef _Included_com_edwardyung_jnilbs_c_jnilbs_MainActivity
#define _Included_com_edwardyung_jnilbs_c_jnilbs_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edwardyung_jnilbs_c_jnilbs_MainActivity
 * Method:    solveRetargeting
 * Signature: ([[F[[I[[F[F)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_com_edwardyung_jnilbs_c_1jnilbs_MainActivity_solveRetargeting
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
