/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_root_retargeter_BitmapRetargeter */

#ifndef _Included_com_example_root_retargeter_BitmapRetargeter
#define _Included_com_example_root_retargeter_BitmapRetargeter
#ifdef __cplusplus
extern "C"
{
#endif
  /*
 * Class:     com_example_root_retargeter_BitmapRetargeter
 * Method:    solveRetargeting
 * Signature: ([[F[[I[[F[F)[[I
 */
  JNIEXPORT jobjectArray JNICALL Java_tech_silvermind_demo_retargeter_BitmapRetargeter_solveRetargeting(JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jfloatArray);

  /*
 * Class:     com_example_root_retargeter_BitmapRetargeter
 * Method:    interpolateImage
 * Signature: ([[F[[III)[[I
 */
  JNIEXPORT jobjectArray JNICALL Java_tech_silvermind_demo_retargeter_BitmapRetargeter_interpolateImage(JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
